const experiences = [
  {
    company: "VCCloud - VCCorp",
    title: "Full Stack Developer",
    type: "Full Time",
    start: "2/2020",
    end: "",
    location: "Hà Nội, Việt Nam",
    bgColor: "light-yellow",
  },
  {
    company: "iHR Solution",
    title: "Frontend Web Developer",
    type: "Full Time",
    start: "10/2019",
    end: "12/2019",
    location: "Hà Nội, Việt Nam",
    bgColor: "light-green",
  },
  {
    company: "Quant Edge",
    title: "Frontend Web Developer",
    type: "Full Time",
    start: "9/2018",
    end: "10/2019",
    location: "Hà Nội, Việt Nam",
    bgColor: "light-violet",
  },
  {
    company: "Techmaster Vietnam",
    title: "Frontend Web Developer",
    type: "Part Time",
    start: "3/2018",
    end: "5/2018",
    location: "Hà Nội, Việt Nam",
    bgColor: "light-blue",
  },
  {
    company: "Techmaster Vietnam",
    title: "Trainee Developer",
    type: "Part Time",
    start: "7/2016",
    end: "12/2016",
    location: "Hà Nội, Việt Nam",
    bgColor: "light-yellow",
  },
];
